apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codemask
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shubham-singhs2/codemask-gitops
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: codemask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
