apiVersion: v1
kind: Service
metadata:
  name: codemask
  namespace: codemask

spec: 
  selector:
    app: codemask

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

  type: NodePort
